[package]
name = "anglescript-rs"
version = "0.1.0"
authors = ["Michael Pollind <mpollind@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "anglescript"

[build-dependencies]
cc = "1.0.72"
bindgen = "0.59.2"

[dependencies]
bitflags = "0.1"
libc = "0.2.112"